### ISSUE TITLE
Add sensor LM35

### ISSUE THREAD

**Issue by paolocontee** [esphome/feature-requests#1069]
it would be necessary to add between the sensors lm35 in esphome

**Comment by glmnet** [comment]
LM35 is a temperature sensor which outputs a voltage proportionally to temperature right? So 1.0 V means 10º C and 3.4 V means 34º C

ESPHome supports those sensors directly via the ADC (Analog to digital converter sensors) https://esphome.io/components/sensor/adc.html

You might need to do some signal adaptation because the ADC pins voltage range support. If you need help I highly recommend the discord support channel, see Home page readme for the link.
