### ISSUE TITLE
Add Humidity sensor in Climate component

### ISSUE THREAD

**Issue by manju-rn** [esphome/feature-requests#1132]
**Describe the problem you have/What new integration you would like**

Currently the climate component does not have any humidity information displayed. However, most of the temprature sensors do come with humidity information as well. Just like the sensor for the temp, it would be great if the Humidity can also be included
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by fabianschaefer** [comment]
In addition it would be handy to use the climate component for humidity as well. Instead of heating/cooling having humidifying/drying and also show the humidity with % instead of °C in the UI.
I know this can already be achieved by misusing the heating/cooling components, but that looks a bit odd in the frontend.

**Comment by MiguelAngelLV** [comment]
In Home Assistant, climate component support current_humidity  (https://developers.home-assistant.io/docs/core/entity/climate/) , so, EspHome must add to climate component.
