### ISSUE TITLE
Use home-assistant secrets.yaml

### ISSUE THREAD

**Issue by Naesstrom** [esphome/feature-requests#121]
**Describe the problem you have/What new integration you would like**

Either an option or make it standard to use the same secrets.yaml as home-assistant do

**Please describe your use case for this integration and alternatives you've tried:**

Right now according to the faq:

> ESPHome supports (most of) Home Assistant’s YAML configuration directives like !include, !secret. So you can store all your secret WiFi passwords and so on in a file called secrets.yaml **within the directory where the configuration file is**.

It would be a lot easier if it could use the same secrets.yaml that home-assistant uses ie. in the relative path `../secrets.yaml` to the config directory for ESPHome. I'm guessing most people already use that file for storing mqtt username, passwords, ssid etc. and have it added to any .gitignore or travis files!

**Additional context**

**Comment by OttoWinter** [comment]
No, esphome and HA are different projects that just _happen_ to use the same secrets file mechanism and layout.

What you're proposing would be another config option, but unless there's no other way of doing a thing I won't add an option for it (otherwise we'd end up with hindreds of options and no one could find the option they need).

I don't find adding esphome's secret file to ci a problem. Should only be a couple of lines. Plus you can even copy the ha stub secret file to the esphome folder if you want.

gitignore is taken care of by esphome automatically. no need to add it manually.
