### ISSUE TITLE
Question : is IT posible to receive and send UDP packets ?

### ISSUE THREAD

**Issue by gnkarn** [esphome/feature-requests#131]
**Describe the problem you have/What new integration you would like**

Be Able to stream UDP packets from a master , and receive them on more than one client,

**Please describe your use case for this integration and alternatives you've tried:**

I have a master esp that senses gesture apds9960 , also is mqtt enabled , and streams udp packets ( sound samples), to other clients , that transforms those udp streams into light effects ( apa 102) ,  and all is integrated to home assistant.

**Additional context**

Is working well , but would like to improve its reliability ( WiFi and mqtt , sometime disconnects) , and also add ota .

This would be possible by using esphome, as the core , and then add my effects ( insert my own code) to read the udp stream and use th received values( an array of 7  bytes ) , to interact with custom effect on the lamps .

**Comment by OttoWinter** [comment]
You asked this question before (https://github.com/esphome/esphome-core/issues/326) and you got your answer there - I don't see anything that has changed since then.

You can absolutely use UDP with esphome - but with custom code. It's practically impossible to write a UDP component as generic that it supports every use case but is also easier to use than just custom code. I'm closing this issue.
