### ISSUE TITLE
ESP32 camera stream

### ISSUE THREAD

**Issue by artek458** [esphome/feature-requests#156]
**Describe the problem you have/What new integration you would like**

Hi,
 I have set ESP32 camera and configured it with hassio with no problems - works great.
I also wish to add stream from this camera in to shinobi. Is there any rtsp stream or anything else which will allow me to link this camera with Shinobi?

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by OttoWinter** [comment]
> Is there any rtsp stream or anything else which will allow me to link this camera with Shinobi?

There is not, and the ESP will not handle that in ESPHome. What would be possible is a component in Home Assistant that converts the MJPEG stream by esphome into an RTSP stream. However, that would be a separate component in Home Assistant.

(I know there are projects that do RTSP on the ESP32 itself, but those also just convert the MJPEG stream to RTSP internally. But since we have HA, there's no reason to do that on the ESP32 where resources are very limited vs the system HA is running on).
