### ISSUE TITLE
Hass.io/McLighting effects

### ISSUE THREAD

**Issue by JuniorGamingTime** [esphome/feature-requests#169]
**Describe the problem you have/What new integration you would like**
Is there a way to have most of the feature from McLighting using ESPHome? I just wanna have eveything running from home assistant (ik there's integration) but I'm really liking how easy it is to edit and upload new code via ESPHome (so after first flash I could just say update code even via my phone).

**Please describe your use case for this integration and alternatives you've tried:**
I used to use McLighting a used most of the effects and would like use those effects as a dropped down, and also have a animation speed slide in HA just like McLighting let's you do

**Additional context**

**Comment by OttoWinter** [comment]
There is not - esphome has its own addressable light abstraction, that won't work with effects from other libraries.

I will close this issue since what is being asked is not possible.

You can go look in the HA forums in the esphome section, some people already posted their custom addressable effects there, that might help
