### ISSUE TITLE
Add support for MG-AUWF01 (Makegood 2-gang wall switch)

### ISSUE THREAD

**Issue by victorhooi** [esphome/feature-requests#1739]
**Describe the problem you have/What new integration you would like**
I would like to support the Makegood 2-gang wall switches - e.g.: MG-AUWF01

**Please describe your use case for this integration and alternatives you've tried:**

I can confirm that Tasmota is flashable onto these devices, if that helps start things at all - this is the Blakadder template page:

https://templates.blakadder.com/makegood_MG-AUWF01.html

Also - I believe there's ESPHome for a similar device:

https://www.esphome-devices.com/devices/Make-Good-MG-MD04W-4-Gang-Wifi-Switch-with-Power-Monitoring

**Additional context**

**Comment by nagyrobi** [comment]
Since you know all the GPIOs from blakadder, all you have to do is to write your own yaml for the device.
Browse trhough https://www.esphome-devices.com/type/plug you'll likely find very similar ones, you just adapt the GPIOs. Energy monitoring may need some extra work due to calibration but since you own the device, it's only you who can do it...
