### ISSUE TITLE
LYWSD03MMC Reed switch support

### ISSUE THREAD

**Issue by Falcon4Tech** [esphome/feature-requests#2140]
**Describe the problem you have/What new integration you would like**

After modification, the sensor has ability to read the status of the reed switch. It can also be programmed in pvvx custom firmware. But is not possible to add integration in ESP. 

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

![IMG_3629](https://user-images.githubusercontent.com/108786187/222269971-d4895f8d-7100-4af7-aa88-ec481574a3df.jpeg)

**Comment by agittins** [comment]
If you just want to be able to access the switch status in homeassistant, you could set the pvvx device to use BTHome advertising format and enable the bluetooth_proxy component in esphome. The esp should then relay the advertisements on to HA which will automatically prompt you to add the bthome integration (I haven't tested the reed switch part of this myself yet, only the basic thermo/baro features).

That way you can also use multiple esphome devices as proxies so that you have sufficient bluetooth reception coverage over your entire house.

If you have a use-case that specifically needs it all to happen on the esphome though, then yes you'll need the pvvx component in esphome to support it which as far as I know it doesn't. I'd strongly suggest considering ble-proxy though, it solves a lot of headaches, and I suspect will be the main way forward.

**Comment by Falcon4Tech** [comment]
Thank you for pointing the way. In fact, through BTHome all statuses are visible. I didn't expect the reed switch is reported immediately, it gives much more possibilities.
