### ISSUE TITLE
DSC Keybus library support

### ISSUE THREAD

**Issue by mzac** [esphome/feature-requests#34]
It would be very interesting to integrate this DSC Keybus library into esphomelib/esphomeyaml:

https://github.com/taligentx/dscKeybusInterface

Not sure how difficult it would be but then it could be a lot easier to configure an ESP8266 to talk to a DSC alarm panel!

**Comment by akomelj** [comment]
It is possible to wrap DSC keybus library with a custom component that can - in turn - be used for reporting alarm status and arming/disarming the system. I've been successfully using this method for the past few months so I'm sharing a quick guide how to do it. Please note that some technical knowledge and understanding of ESPHome custom components is needed when going down this route and these instructions are not intended for the beginners.

I attached two C++ files that implement the needed custom component. GitHub does not allow attaching C++ sources, *sigh*, so here's a ZIP file instead: [dsc.zip](https://github.com/esphome/feature-requests/files/4333308/dsc.zip)

Now, the idea behind using this custom component is the following:

- the component initializes `dscKeybusInterface` and calls its `begin()` and `loop()` methods
- the component allows for registration of "callbacks" for the most common alarm status changes
- these callbacks use ESPHome template sensors and switches to report alarm system state 

Attached component code is sufficiently documented to help you get started, but a few examples of the above principles can't hurt.

Component is initialized according to ESPHome custom component guide. Constructor parameters are documented in `dsc.h` header file.

```
custom_component:
  - lambda: |-
      // initialize global DSC interface
      aember::dsc = new aember::Dsc(${dscClockPin}, ${dscReadPin}, ${dscWritePin}, ${dscPartitions}, ${dscZones}, ${dscAccessCode}, ${dscMasterCode});

      // register the component
      App.register_component(aember::dsc);
      return { aember::dsc };
```

Now, once the component is initialized, you can register callbacks for alarm state changes. For example:

```
      // publish partition changes as they happen
      aember::dsc->onStatusChange([&](uint8_t partition, uint8_t status, std::string message) { 
        switch(partition) {
          case 0: id(partition1_status).publish_state(message); break;
          // NOTE: add more partitions here
        }
      });
```

In order for the code above to work, a `partition1_status` template sensor is needed in your ESPHome yaml:

```
text_sensor:
  # DSC partition 1 status text sensor
  - platform: template
    name: partition1_status
    id: partition1_status
    lambda: return {};
```

For arm/disarm switches, the logic is similar.

```
      aember::dsc->onArmedChange([&](uint8_t partition, bool isArmed) {
        switch(partition) {
          case 0:
            id(partition1_armed_away).publish_state(aember::dsc->getDsc().armedAway[0]);
            id(partition1_armed_stay).publish_state(aember::dsc->getDsc().armedStay[0]);
            break;
          // NOTE: add more partitions here
        }
      });
```

The template switches (`partition1_armed_away`, `partition1_armed_stay`) are defined similarly to sensor switches, with an addition of automation lambda that allows you to arm/disarm the system:

```
switch:
  # DSC partition 1 armed away switch
  - platform: template
    name: partition1_armed_away
    id: partition1_armed_away
    lambda: return {};
    turn_on_action:
      - lambda: |-
          ESP_LOGI(aember::Dsc::TAG, "Arming partition 1 - AWAY");
          aember::dsc->getDsc().writePartition = 1;
          aember::dsc->getDsc().write('w');
    turn_off_action:
      - lambda: |-
          ESP_LOGI(aember::Dsc::TAG, "Disarming partition 1");
          aember::dsc->getDsc().writePartition = 1;
          aember::dsc->getDsc().write(${dscAccessCode});
```

And this is basically it. Feel free to copy & paste and hack to pieces for your system. I'm attaching a sample yaml file from my system (1 partition, 7 zones) - 
[dsc.yaml.zip](https://github.com/esphome/feature-requests/files/4333339/dsc.yaml.zip)

Please note that I'm building all my ESPHome yaml files with some "common" sections (those `!include` keywords in the file) so you won't find configuration of common sensors and switches in this file and you can't simply build the attached yaml. That's why the warning, that some technical experience is needed. :-)

A few important NOTES if someone still decides to waste time implementing this. :-)

- `/develop` branch of `dscKeybusInterface` is needed as keybus connection management interface is not available in the last releases version; clone the library repo locally, checkout the `/develop` branch and add library path to ESPHome libraries section (see the attached yaml or ESPHome docs for details)
- Keybus connection management interface is needed if you wish to perform OTA updates. It is absolutely mandatory that you disconnect the interface from the keybus before performing OTA updates - otherwise the library's keybus interrupt handling routines will mess with your OTA transfer and just lock-up/reboot the device
- I've observed some strange behaviour of the keybus library interface on my installation immediately after startup and have implemented two hacks two 
   - alarm system trouble is reported although there is none; the component therefore discards the initial "trouble changed" event and keeps checking and posting the trouble state every minute even if the trouble state doesn't change;
   - the 1st `dsc.loop()` call after restart arms my system. I suspect a bug in the library as I was experimenting with various boot-up PIN states and couldn't reproduce it. I'm fairly certain the library sends some data on the keybus when enabled, therefore the component starts the interface with "write to partition 2" setting and later switches to (my one and only) partition 1 when needed. If you have more than one partition, this "hack" my arm your partition 2 after restart.

Good luck. :-)
