### ISSUE TITLE
Icons based on state for binary sensors

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [esphome/feature-requests#409]
**Describe the problem you have/What new integration you would like**

Ability to have 2 different icons displaying based on a binary sensor state
**Please describe your use case for this integration and alternatives you've tried:**

```
Here is how this could be implemented
icon_on: "mdi:water"
icon_off: "mdi:water-off"
Of course, this can also be done with customisation on HA, but it could be nice to have this directly within ESPHome
**Additional context**
<!-- Add any other context about the feature request here. -->


<!-- LEAVE THIS LINE AS-IS AND DON'T DELETE IT, OTHERWISE THE FEATURE REQUEST WILL BE CLOSED AUTOMATICALLY. -->

**Comment by OttoWinter** [comment]
That is a frontend concern - esphome only delivers data to Home Assistant, what/how HA chooses to display that is up to HA (also because ESPHome is universal, and not just for HA).

One option would be to create a template binary sensor in Home Assistant that mirrors the state of the original binary sensor and has an additional icon_template set.
