### ISSUE TITLE
Brightness option to light.addressable_set

### ISSUE THREAD

**Issue by marrobHD** [esphome/feature-requests#426]
**Describe the problem you have/What new integration you would like**

 Add a brightness option to light.addressable_set. 

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

Nothing else

**Comment by OttoWinter** [comment]
Well brightness is the exact same as multiplying r, g and b with a value.

In order to avoid user confusion I have deliberately left out brightness for adressable_set (if there are two ways to influence brightness, rgb values *and* brightness parameter users get confused, as seen with the other light automations).
