### ISSUE TITLE
Get board info with command line

### ISSUE THREAD

**Issue by ng-galien** [esphome/feature-requests#503]
**Describe the problem you have/What new integration you would like**

Add an option in the esphome command line to get information about the hardware device, especially the flash.
**Please describe your use case for this integration and alternatives you've tried:**

Because somehow are facing problems probably related to specific hardware (such as chinese copy of well known devices), it will help in order to solve issues. I someone is struggling with a xxxx device and others no, we have to be sure that's exactly the same hardware with the same hardware configuration.

Gathering informations form esptool flash_id can be a good start.

Had this mention on issue template.

The command can be something like
`esphome info`

**Additional context**

Nothing.
And thanks for considering this request.

**Comment by OttoWinter** [comment]
So if you download esphome-flasher, you already get this information.

Additionally, esptool.py is a dependency of esphome, so when you install esphome you also have esptool.py installed automatically. That means you can also run the flash_id command easily through that.

So since the capability is very easy to access already, I don't think a new command is needed.
