### ISSUE TITLE
esphome cannot go into deep sleep if it does not see wifi

### ISSUE THREAD

**Issue by VanGog86** [esphome/feature-requests#727]
**Describe the problem you have/What new integration you would like**

Good afternoon.
I make a Wi-Fi thermometer on a battery, and I ran into a problem, the house turned off the electricity, the thermometer woke up from a deep sleep, could not connect to wifi (since the router was turned off), and without stopping, I tried to find the network without going to sleep. as a result, the battery has run out.
It would be great if esphome could, in the absence of wifi proto go to sleep.
The same problem with MQTT if the mosquito on the homeassistant is turned off, then esphome goes into the mosquito search cycle, there I discharge the battery
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by spattinson** [comment]
This happens because run_duration does not start counting until mqtt is connected. This is by design whether you agree with it or not, so you have to run your own timer and invoke deep_sleep yourself if wifi or mqtt do not connect. Below is a config I use, I use an automation in home assistant that publishes an MQTT packet to put to sleep as soon as a sensor reading is uploaded, if mqtt connects but home assistant is down run_duration will be reached, if mqtt/wifi is down the on_boot timer catches that and goes to sleep. The advantage of using an automation to go to sleep is that you can change it to prevent deep sleep to perform ota uploads. Setting blank birth/will messages prevents home assistant marking the node as unavailable when it is sleeping, and spamming your logbook

I would be interested in any feedback on my approach to this from devs or others. What I am doing here works reliably for me for a sensor at a remote location over a cellular internet connection. It took me a while to cater for all the failure modes and avoid unnecessary battery discharge. 
```
esphome:
  name: bedford
  platform: ESP32
  board: esp32dev
  on_boot:
    # If MQTT cant connect in 30s will deep sleep
    priority: 500
    then:
      - delay: 30s
      - if:
          condition:
            binary_sensor.is_off: bedford_status
          then:
            - deep_sleep.enter: deep_sleep_1

wifi:
  ssid: xxx
  password: yyy
  fast_connect: true

mqtt:
  broker: zzz
  port: nnn
  username: uuu
  password: ppp
  birth_message:
  will_message:
  on_message:
    # Prevent deep sleep for OTA
    - topic: bedford/ota_mode
      payload: 'ON'
      then:
        - deep_sleep.prevent: deep_sleep_1
    # Home Assistant Automation Puts to sleep after measurements
    - topic: bedford/sleep_mode
      payload: 'ON'
      then:
        - deep_sleep.enter: deep_sleep_1

logger:
  level: NONE

ota:
  password: fileybay

i2c:
  sda: 16
  scl: 17

binary_sensor:
  - platform: status
    name: "bedford_status"
    id: bedford_status

sensor:
 ...

deep_sleep:
  id: deep_sleep_1
  # If MQTT is connected but Home Assistant is down this will be reached
  run_duration: 10s
  sleep_duration: 60min
