### ISSUE TITLE
Documentation and Feature Requests RE Display Pages

### ISSUE THREAD

**Issue by davericher** [esphome/feature-requests#76]
**Describe the problem you have/What new integration you would like**
In regards to Display Pages:
- Documentation
- The ability to get current page 'number', I realize the ids from ESPHOME translate into variable names, but possibly store them internally and expose them as a public getter off the DISPLAY object (display->currentPage) 
- Rather then having a one or the other approach in regards to a top level lambda and pages, perhaps have the top level lambda act as a master, for example if you were to draw UI elements such has bars and indicators that would appear on every page, this would reduce duplication 

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

**Comment by OttoWinter** [comment]
1. Yes, will add that
2. I don't think I will add a page "number" (because everything's stored as a linked list internally), but I guess it can't hurt to add an option to get the currently active page as an object.
3. That sounds a bit too little flexible for me. What if a user wants to show some overlay on every page but one? Besides the solution to this is quite easy:

a) Add a method in a file and include it with `esphome.includes`
b) Create a substitution with the common lambda content and use it in each page lambda with $common_code
