### ISSUE TITLE
'Pause' devices that are intentionally offline.

### ISSUE THREAD

**Issue by StyxyDog** [esphome/feature-requests#88]
**Describe the problem you have/What new integration you would like**

I'd like to be able to 'pause' esp devices that are currently not working or purposely offline. I get a lot of INFO messages in my log about ESPHome API not being able to connect to a certain device. Usually its because its on the workbench in pieces or it was part of an ongoing experiment that I intend to come back to. I'd like to be able to keep the device in the list without it being active.

**Please describe your use case for this integration and alternatives you've tried:**

Errors in my HA log due to a device in ESPHome being intentionally offline.

`INFO (MainThread) [homeassistant.components.esphome] Can't connect to ESPHome API for 192.168.1.130: Error connecting to ('192.168.1.130', 6053): [Errno 113] Connect call failed ('192.168.1.130', 6053)`

**Additional context**

Its bells and whistles really because ESPHome is fantastic. Thanks for all your hard work on this.

Maybe like this...
![screenshot 2019-02-28 at 09 33 42](https://user-images.githubusercontent.com/44403187/53556560-03d6dc00-3b3c-11e9-9642-d4a07c0ba25b.png)

**Comment by OttoWinter** [comment]
No I won't implement this.

The Home Assistant config is intentionally bare minimum, and my goal is to never have any config options for esphome in HA. All options must be specified directly on the ESP and will be transmitted to HA on connect.

Because this transmission is oc impossible when the device is offline, I will decline this feature request. I would suggest just removing the integration with the delete icon in the top right corner.
