### ISSUE TITLE
Total daily energy

### ISSUE THREAD

**Issue by r-jordan** [esphome/feature-requests#9]
**Is your feature request related to a problem/use-case? Please describe.**

I cannot sum the energy used in different hours that have different prices.

**Describe the solution you'd like:**

I would like to have more than one total energy sensors that could be used in different hours that have different prices of the energy. For example, to have one sensor for counting the energy used from 12:00 to 22:00 and the other sensor for the rest of hours.

**Additional context:**

A work around would be a way of resetting the energy sensor sum to 0.

**Comment by OttoWinter** [comment]
I'm gonna close this because HA now has integrations now that allow something like that much better:

- https://www.home-assistant.io/components/utility_meter/
- https://www.home-assistant.io/components/sensor.integration/

And if HA has such integrations already I don't think there's really a reason to have them in ESPHome.
